BEGIN;

-- ============================================================================
-- SUKUU STAGE 3B PHASE 2C
-- Controlled Credential Bootstrap Foundation
--
-- No fixed password is created by this migration.
--
-- A credential challenge:
--   - contains only a cryptographic HASH of the one-time token
--   - is single-use
--   - expires
--   - is revocable
--   - cannot be read directly by the application runtime
--
-- The plaintext activation token exists only at issuance time and must be
-- transferred to the authorised account holder out-of-band.
-- ============================================================================


-- --------------------------------------------------------------------------
-- 1. Preconditions.
-- --------------------------------------------------------------------------

DO $preflight$
BEGIN

  IF to_regclass(
    'system.system_user'
  ) IS NULL THEN
    RAISE EXCEPTION
      'Phase 2C aborted: system_user table missing';
  END IF;


  IF to_regclass(
    'system.system_password_history'
  ) IS NULL THEN
    RAISE EXCEPTION
      'Phase 2C aborted: password-history table missing';
  END IF;


  IF to_regclass(
    'system.system_session'
  ) IS NULL THEN
    RAISE EXCEPTION
      'Phase 2C aborted: session table missing';
  END IF;


  IF to_regprocedure(
    'system._auth_password_matches(text,text)'
  ) IS NULL THEN
    RAISE EXCEPTION
      'Phase 2C aborted: database password verifier missing';
  END IF;

END
$preflight$;


-- --------------------------------------------------------------------------
-- 2. One-time credential challenges.
-- --------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS
  system.system_credential_challenge
(
  id uuid
    PRIMARY KEY
    DEFAULT gen_random_uuid(),

  user_id text
    NOT NULL,

  school_id text
    NOT NULL,

  purpose text
    NOT NULL,

  token_hash text
    NOT NULL,

  issued_by text,

  created_at timestamptz
    NOT NULL
    DEFAULT CURRENT_TIMESTAMP,

  expires_at timestamptz
    NOT NULL,

  consumed_at timestamptz,

  revoked_at timestamptz,

  attempt_count integer
    NOT NULL
    DEFAULT 0,

  max_attempts integer
    NOT NULL
    DEFAULT 5,

  CONSTRAINT
    system_credential_challenge_purpose_check
  CHECK (
    purpose IN (
      'FIRST_CREDENTIAL',
      'PASSWORD_RESET',
      'COMPROMISED_ROTATION'
    )
  ),

  CONSTRAINT
    system_credential_challenge_attempt_check
  CHECK (
    attempt_count >= 0
    AND max_attempts BETWEEN 1 AND 20
  )
);


CREATE UNIQUE INDEX IF NOT EXISTS
  uq_system_credential_challenge_token_hash
ON
  system.system_credential_challenge
  (token_hash);


CREATE UNIQUE INDEX IF NOT EXISTS
  uq_system_credential_challenge_open_user
ON
  system.system_credential_challenge
  (user_id)
WHERE
  consumed_at IS NULL
  AND revoked_at IS NULL;


CREATE INDEX IF NOT EXISTS
  idx_system_credential_challenge_school
ON
  system.system_credential_challenge
  (school_id);


CREATE INDEX IF NOT EXISTS
  idx_system_credential_challenge_expiry
ON
  system.system_credential_challenge
  (expires_at);


ALTER TABLE
  system.system_credential_challenge
ENABLE ROW LEVEL SECURITY;


ALTER TABLE
  system.system_credential_challenge
FORCE ROW LEVEL SECURITY;


REVOKE ALL
ON TABLE
  system.system_credential_challenge
FROM PUBLIC;


DO $runtime_table_lock$
BEGIN

  IF EXISTS (
    SELECT 1
    FROM pg_catalog.pg_roles
    WHERE rolname='sukuu_app_runtime'
  ) THEN

    EXECUTE
      'REVOKE ALL ON TABLE system.system_credential_challenge FROM sukuu_app_runtime';

  END IF;

END
$runtime_table_lock$;


-- --------------------------------------------------------------------------
-- 3. Raise current tenant password-policy floor.
--
-- We do not alter the existing expiry interval here.
-- --------------------------------------------------------------------------

UPDATE
  system.system_password_policy

SET
  min_length =
    GREATEST(min_length,12),

  require_uppercase = true,
  require_lowercase = true,
  require_numbers = true,
  require_symbols = true;


-- --------------------------------------------------------------------------
-- 4. Redeem one credential challenge.
--
-- p_new_password is used only for password-history comparison and is NEVER
-- persisted.
--
-- p_new_password_hash is the bcrypt hash generated by the API.
-- --------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION
  system.auth_redeem_credential_challenge(
    p_token_hash text,
    p_new_password text,
    p_new_password_hash text
  )
RETURNS jsonb
LANGUAGE plpgsql
VOLATILE
SECURITY DEFINER
SET search_path =
  pg_catalog,
  system,
  sukuux
AS $function$

DECLARE

  v_challenge
    system.system_credential_challenge%ROWTYPE;

  v_user
    system.system_user%ROWTYPE;

BEGIN

  IF
    p_token_hash IS NULL
    OR length(p_token_hash) <> 64
    OR p_new_password IS NULL
    OR p_new_password_hash IS NULL
  THEN

    RETURN jsonb_build_object(
      'ok',
      false,
      'reason',
      'INVALID'
    );

  END IF;


  -- Defence in depth.
  -- The API performs the same rules before bcrypt hashing.

  IF
    length(p_new_password) < 12
    OR p_new_password !~ '[A-Z]'
    OR p_new_password !~ '[a-z]'
    OR p_new_password !~ '[0-9]'
    OR p_new_password !~ '[^A-Za-z0-9]'
  THEN

    RETURN jsonb_build_object(
      'ok',
      false,
      'reason',
      'WEAK_PASSWORD'
    );

  END IF;


  SELECT
    c.*

  INTO
    v_challenge

  FROM
    system.system_credential_challenge c

  WHERE
    c.token_hash = p_token_hash

  LIMIT 1

  FOR UPDATE;


  IF NOT FOUND THEN

    RETURN jsonb_build_object(
      'ok',
      false,
      'reason',
      'INVALID'
    );

  END IF;


  IF
    v_challenge.consumed_at IS NOT NULL
    OR v_challenge.revoked_at IS NOT NULL
    OR v_challenge.expires_at <= CURRENT_TIMESTAMP
    OR v_challenge.attempt_count >=
       v_challenge.max_attempts
  THEN

    RETURN jsonb_build_object(
      'ok',
      false,
      'reason',
      'INVALID'
    );

  END IF;


  SELECT
    u.*

  INTO
    v_user

  FROM
    system.system_user u

  WHERE
    u.id =
      v_challenge.user_id
    AND u.archived_at IS NULL

  LIMIT 1

  FOR UPDATE;


  IF NOT FOUND
     OR v_user.status IN (
       'SUSPENDED',
       'CLOSED'
     )
  THEN

    UPDATE
      system.system_credential_challenge

    SET
      revoked_at =
        COALESCE(
          revoked_at,
          CURRENT_TIMESTAMP
        )

    WHERE
      id = v_challenge.id;


    RETURN jsonb_build_object(
      'ok',
      false,
      'reason',
      'INVALID'
    );

  END IF;


  -- Prevent reuse of current credential.

  IF system._auth_password_matches(
       p_new_password,
       v_user.password_hash
     )
  THEN

    UPDATE
      system.system_credential_challenge

    SET
      attempt_count =
        attempt_count + 1

    WHERE
      id = v_challenge.id;


    RETURN jsonb_build_object(
      'ok',
      false,
      'reason',
      'PASSWORD_REUSED'
    );

  END IF;


  -- Prevent reuse of any captured password-history credential.

  IF EXISTS (

    SELECT 1

    FROM
      system.system_password_history h

    WHERE
      h.user_id = v_user.id

      AND system._auth_password_matches(
        p_new_password,
        h.password_hash
      )

  ) THEN

    UPDATE
      system.system_credential_challenge

    SET
      attempt_count =
        attempt_count + 1

    WHERE
      id = v_challenge.id;


    RETURN jsonb_build_object(
      'ok',
      false,
      'reason',
      'PASSWORD_REUSED'
    );

  END IF;


  -- Preserve the credential being replaced.

  INSERT INTO
    system.system_password_history
  (
    id,
    user_id,
    password_hash,
    created_at
  )
  VALUES
  (
    gen_random_uuid()::text,
    v_user.id,
    v_user.password_hash,
    CURRENT_TIMESTAMP
  );


  -- Establish the new credential.

  UPDATE
    system.system_user

  SET
    password_hash =
      p_new_password_hash,

    is_active = true,
    is_verified = true,

    must_reset_password = false,

    failed_login_count = 0,
    locked_until = NULL,

    status =
      CASE

        WHEN status IN (
          'INVITED',
          'PENDING_VERIFICATION',
          'LOCKED'
        )
        THEN 'ACTIVE'

        ELSE status

      END,

    row_version =
      row_version + 1,

    updated_at =
      CURRENT_TIMESTAMP

  WHERE
    id = v_user.id;


  -- Credential establishment invalidates every existing session.

  UPDATE
    system.system_session

  SET
    is_active = false,

    invalidated_at =
      COALESCE(
        invalidated_at,
        CURRENT_TIMESTAMP
      ),

    last_activity_at =
      CURRENT_TIMESTAMP

  WHERE
    user_id = v_user.id
    AND is_active = true;


  -- Consume this challenge.

  UPDATE
    system.system_credential_challenge

  SET
    consumed_at =
      CURRENT_TIMESTAMP

  WHERE
    id = v_challenge.id;


  -- Revoke any other challenge for this identity.

  UPDATE
    system.system_credential_challenge

  SET
    revoked_at =
      CURRENT_TIMESTAMP

  WHERE
    user_id = v_user.id

    AND id <>
      v_challenge.id

    AND consumed_at IS NULL
    AND revoked_at IS NULL;


  -- Security evidence.

  INSERT INTO
    system.system_audit_event
  (
    id,
    user_id,
    school_id,
    action,
    entity_type,
    entity_id,
    before_state,
    after_state,
    created_at
  )
  VALUES
  (
    gen_random_uuid()::text,
    v_user.id,
    v_challenge.school_id,
    'CREDENTIAL_ESTABLISHED',
    'system_user',
    v_user.id,
    NULL,
    jsonb_build_object(
      'purpose',
      v_challenge.purpose
    )::text,
    CURRENT_TIMESTAMP
  );


  RETURN jsonb_build_object(
    'ok',
    true
  );

END
$function$;


REVOKE ALL
ON FUNCTION
  system.auth_redeem_credential_challenge(
    text,
    text,
    text
  )
FROM PUBLIC;


DO $runtime_function_grant$
BEGIN

  IF EXISTS (
    SELECT 1
    FROM pg_catalog.pg_roles
    WHERE rolname='sukuu_app_runtime'
  ) THEN

    EXECUTE
      'GRANT EXECUTE ON FUNCTION system.auth_redeem_credential_challenge(text,text,text) TO sukuu_app_runtime';

  END IF;

END
$runtime_function_grant$;



-- --------------------------------------------------------------------------
-- 5. Password-history credential vault.
--
-- Password hashes are security-verification material, not ordinary
-- tenant-readable business records.
--
-- Direct application access is removed. Credential comparison and history
-- maintenance occur only through controlled SECURITY DEFINER functions.
-- --------------------------------------------------------------------------

ALTER TABLE
  system.system_password_history
ENABLE ROW LEVEL SECURITY;


ALTER TABLE
  system.system_password_history
FORCE ROW LEVEL SECURITY;


DROP POLICY IF EXISTS
  own_or_colleague
ON
  system.system_password_history;


REVOKE ALL
ON TABLE
  system.system_password_history
FROM PUBLIC;


DO $password_history_runtime_lock$
BEGIN

  IF EXISTS (
    SELECT 1
    FROM pg_catalog.pg_roles
    WHERE rolname='sukuu_app_runtime'
  ) THEN

    EXECUTE
      'REVOKE ALL ON TABLE system.system_password_history FROM sukuu_app_runtime';

  END IF;

END
$password_history_runtime_lock$;


-- --------------------------------------------------------------------------
-- 6. Trusted own-password change.
--
-- The application never receives stored password-history hashes.
--
-- A valid HMAC-backed authenticated session is required through ctx_user_id()
-- and ctx_school_id().
--
-- Successful password change:
--   - verifies the existing password
--   - applies tenant password policy with a 12-character security floor
--   - rejects current/history reuse
--   - archives the replaced credential hash
--   - changes the password
--   - clears authentication lock state
--   - invalidates ALL existing sessions
--   - records security evidence
-- --------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION
  system.auth_change_own_password(
    p_current_password text,
    p_new_password text,
    p_new_password_hash text
  )
RETURNS jsonb
LANGUAGE plpgsql
VOLATILE
SECURITY DEFINER
SET search_path =
  pg_catalog,
  system,
  sukuux
AS $function$

DECLARE

  v_user_id text;
  v_school_id text;

  v_user
    system.system_user%ROWTYPE;

  v_min_length integer := 12;

  v_require_uppercase boolean := true;
  v_require_lowercase boolean := true;
  v_require_numbers boolean := true;
  v_require_symbols boolean := true;

BEGIN

  v_user_id :=
    system.ctx_user_id();

  v_school_id :=
    system.ctx_school_id();


  IF
    v_user_id IS NULL
    OR v_school_id IS NULL
  THEN

    RETURN jsonb_build_object(
      'ok',
      false,
      'reason',
      'INVALID_SESSION'
    );

  END IF;


  SELECT
    u.*

  INTO
    v_user

  FROM
    system.system_user u

  WHERE
    u.id = v_user_id
    AND u.archived_at IS NULL

  LIMIT 1

  FOR UPDATE;


  IF NOT FOUND THEN

    RETURN jsonb_build_object(
      'ok',
      false,
      'reason',
      'INVALID_SESSION'
    );

  END IF;


  IF
    v_user.is_active IS NOT TRUE
    OR v_user.status IN (
      'SUSPENDED',
      'CLOSED',
      'LOCKED'
    )
  THEN

    RETURN jsonb_build_object(
      'ok',
      false,
      'reason',
      'ACCOUNT_BLOCKED'
    );

  END IF;


  IF NOT system._auth_password_matches(
    p_current_password,
    v_user.password_hash
  ) THEN

    RETURN jsonb_build_object(
      'ok',
      false,
      'reason',
      'CURRENT_PASSWORD_INVALID'
    );

  END IF;


  SELECT

    COALESCE(
      (
        SELECT
          GREATEST(
            p.min_length,
            12
          )

        FROM
          system.system_password_policy p

        WHERE
          p.school_id = v_school_id

        LIMIT 1
      ),
      12
    ),

    COALESCE(
      (
        SELECT
          p.require_uppercase

        FROM
          system.system_password_policy p

        WHERE
          p.school_id = v_school_id

        LIMIT 1
      ),
      true
    ),

    COALESCE(
      (
        SELECT
          p.require_lowercase

        FROM
          system.system_password_policy p

        WHERE
          p.school_id = v_school_id

        LIMIT 1
      ),
      true
    ),

    COALESCE(
      (
        SELECT
          p.require_numbers

        FROM
          system.system_password_policy p

        WHERE
          p.school_id = v_school_id

        LIMIT 1
      ),
      true
    ),

    COALESCE(
      (
        SELECT
          p.require_symbols

        FROM
          system.system_password_policy p

        WHERE
          p.school_id = v_school_id

        LIMIT 1
      ),
      true
    )

  INTO
    v_min_length,
    v_require_uppercase,
    v_require_lowercase,
    v_require_numbers,
    v_require_symbols;


  IF
    p_new_password IS NULL
    OR length(p_new_password) <
       v_min_length
    OR (
      v_require_uppercase
      AND p_new_password !~ '[A-Z]'
    )
    OR (
      v_require_lowercase
      AND p_new_password !~ '[a-z]'
    )
    OR (
      v_require_numbers
      AND p_new_password !~ '[0-9]'
    )
    OR (
      v_require_symbols
      AND p_new_password !~ '[^A-Za-z0-9]'
    )
  THEN

    RETURN jsonb_build_object(
      'ok',
      false,
      'reason',
      'WEAK_PASSWORD'
    );

  END IF;


  IF system._auth_password_matches(
    p_new_password,
    v_user.password_hash
  ) THEN

    RETURN jsonb_build_object(
      'ok',
      false,
      'reason',
      'PASSWORD_REUSED'
    );

  END IF;


  IF EXISTS (

    SELECT 1

    FROM
      system.system_password_history h

    WHERE
      h.user_id =
        v_user.id

      AND system._auth_password_matches(
        p_new_password,
        h.password_hash
      )

  ) THEN

    RETURN jsonb_build_object(
      'ok',
      false,
      'reason',
      'PASSWORD_REUSED'
    );

  END IF;


  INSERT INTO
    system.system_password_history
  (
    id,
    user_id,
    password_hash,
    created_at
  )
  VALUES
  (
    gen_random_uuid()::text,
    v_user.id,
    v_user.password_hash,
    CURRENT_TIMESTAMP
  );


  UPDATE
    system.system_user

  SET
    password_hash =
      p_new_password_hash,

    must_reset_password =
      false,

    failed_login_count =
      0,

    locked_until =
      NULL,

    row_version =
      row_version + 1,

    updated_at =
      CURRENT_TIMESTAMP

  WHERE
    id = v_user.id;


  UPDATE
    system.system_session

  SET
    is_active =
      false,

    invalidated_at =
      COALESCE(
        invalidated_at,
        CURRENT_TIMESTAMP
      ),

    last_activity_at =
      CURRENT_TIMESTAMP

  WHERE
    user_id = v_user.id
    AND is_active = true;


  INSERT INTO
    system.system_audit_event
  (
    id,
    user_id,
    school_id,
    action,
    entity_type,
    entity_id,
    before_state,
    after_state,
    created_at
  )
  VALUES
  (
    gen_random_uuid()::text,
    v_user.id,
    v_school_id,
    'PASSWORD_CHANGED',
    'system_user',
    v_user.id,
    NULL,
    jsonb_build_object(
      'allSessionsRevoked',
      true
    )::text,
    CURRENT_TIMESTAMP
  );


  RETURN jsonb_build_object(
    'ok',
    true
  );

END
$function$;


REVOKE ALL
ON FUNCTION
  system.auth_change_own_password(
    text,
    text,
    text
  )
FROM PUBLIC;


DO $password_change_runtime_grant$
BEGIN

  IF EXISTS (
    SELECT 1
    FROM pg_catalog.pg_roles
    WHERE rolname='sukuu_app_runtime'
  ) THEN

    EXECUTE
      'GRANT EXECUTE ON FUNCTION system.auth_change_own_password(text,text,text) TO sukuu_app_runtime';

  END IF;

END
$password_change_runtime_grant$;


-- --------------------------------------------------------------------------
-- 7. Credential-vault postconditions.
-- --------------------------------------------------------------------------

DO $credential_vault_postcheck$
BEGIN

  IF to_regprocedure(
    'system.auth_change_own_password(text,text,text)'
  ) IS NULL THEN

    RAISE EXCEPTION
      'Phase 2C post-check failed: trusted password-change function missing';

  END IF;


  IF EXISTS (
    SELECT 1

    FROM pg_catalog.pg_policies

    WHERE
      schemaname='system'
      AND tablename='system_password_history'
      AND policyname='own_or_colleague'
  ) THEN

    RAISE EXCEPTION
      'Phase 2C post-check failed: legacy password-history policy remains';

  END IF;


  IF EXISTS (
    SELECT 1
    FROM pg_catalog.pg_roles
    WHERE rolname='sukuu_app_runtime'
  )
  AND (
    has_table_privilege(
      'sukuu_app_runtime',
      'system.system_password_history',
      'SELECT'
    )
    OR
    has_table_privilege(
      'sukuu_app_runtime',
      'system.system_password_history',
      'INSERT'
    )
    OR
    has_table_privilege(
      'sukuu_app_runtime',
      'system.system_password_history',
      'UPDATE'
    )
    OR
    has_table_privilege(
      'sukuu_app_runtime',
      'system.system_password_history',
      'DELETE'
    )
  ) THEN

    RAISE EXCEPTION
      'Phase 2C post-check failed: runtime retains direct password-history table access';

  END IF;

END
$credential_vault_postcheck$;


-- --------------------------------------------------------------------------
-- 8. Postconditions.
-- --------------------------------------------------------------------------

DO $postcheck$
BEGIN

  IF to_regclass(
    'system.system_credential_challenge'
  ) IS NULL THEN

    RAISE EXCEPTION
      'Phase 2C post-check failed: challenge table missing';

  END IF;


  IF to_regprocedure(
    'system.auth_redeem_credential_challenge(text,text,text)'
  ) IS NULL THEN

    RAISE EXCEPTION
      'Phase 2C post-check failed: redemption function missing';

  END IF;

END
$postcheck$;


COMMIT;
