import { Router } from 'express';
import { authenticate } from '../../middleware/authenticate';
import { requireModuleAccess } from '../../middleware/requireModuleAccess';
import * as ctrl from './school.controller';
export const schoolRouter = Router();
const R = requireModuleAccess('school', 'read');
const F = requireModuleAccess('school', 'full');
schoolRouter.get('/profile', authenticate, R, ctrl.getProfile);
schoolRouter.patch('/profile', authenticate, F, ctrl.patchProfile);
schoolRouter.get('/settings', authenticate, R, ctrl.getSettings);
schoolRouter.put('/settings', authenticate, F, ctrl.putSetting);
schoolRouter.patch('/settings/:id/archive', authenticate, F, ctrl.patchArchiveSetting);
schoolRouter.get('/accreditations', authenticate, R, ctrl.getAccreditations);
schoolRouter.post('/accreditations', authenticate, F, ctrl.postAccreditation);
schoolRouter.patch('/accreditations/:accreditationId/archive', authenticate, F, ctrl.patchArchiveAccreditation);
schoolRouter.put('/accreditations/:accreditationId', authenticate, F, ctrl.patchAccreditation);
schoolRouter.get('/audit-log', authenticate, R, ctrl.getSchoolAuditLog);
schoolRouter.get('/contacts', authenticate, R, ctrl.getContacts);
schoolRouter.post('/contacts', authenticate, F, ctrl.postContact);
schoolRouter.patch('/contacts/:id', authenticate, F, ctrl.patchContact);
schoolRouter.get('/branding', authenticate, R, ctrl.getBrandingHandler);
schoolRouter.put('/branding', authenticate, F, ctrl.putBranding);
schoolRouter.get('/campuses', authenticate, R, ctrl.getCampuses);
schoolRouter.post('/campuses', authenticate, F, ctrl.postCampus);
schoolRouter.patch('/campuses/:id', authenticate, F, ctrl.patchCampus);
schoolRouter.put('/campuses/:id', authenticate, F, ctrl.patchCampusDetails);
schoolRouter.get('/term-policy', authenticate, R, ctrl.getTermPolicyHandler);
schoolRouter.put('/term-policy', authenticate, F, ctrl.putTermPolicy);
schoolRouter.get('/documents', authenticate, R, ctrl.getDocuments);
schoolRouter.post('/documents', authenticate, F, ctrl.postDocument);
schoolRouter.get('/subscription', authenticate, R, ctrl.getSubscriptionHandler);
schoolRouter.patch('/subscription', authenticate, F, ctrl.patchSubscription);

schoolRouter.get('/summary', authenticate, R, ctrl.getSummary);
