import { Router } from 'express';
import { authenticate } from '../../middleware/authenticate';
import { requireModuleAccess } from '../../middleware/requireModuleAccess';
import { requireStepUp } from '../../middleware/requireStepUp';
import * as ctrl from './ops.controller';

export const opsRouter = Router();
const R = requireModuleAccess('system', 'read');
const F = requireModuleAccess('system', 'full');
const S = requireStepUp;
opsRouter.get('/config', authenticate, R, ctrl.getConfig);
opsRouter.put('/config', authenticate, F, S, ctrl.putConfig);
opsRouter.get('/environments', authenticate, R, ctrl.getEnvironments);
opsRouter.get('/departments', authenticate, R, ctrl.getDepartments);
opsRouter.post('/departments', authenticate, F, S, ctrl.postDepartment);
opsRouter.get('/integrations', authenticate, R, ctrl.getIntegrations);
opsRouter.post('/integrations', authenticate, F, S, ctrl.postIntegration);
opsRouter.patch('/integrations/:id', authenticate, F, S, ctrl.patchIntegration);
opsRouter.get('/backups', authenticate, R, ctrl.getBackups);
opsRouter.get('/backup-logs', authenticate, R, ctrl.getBackupLogs);
opsRouter.get('/jobs', authenticate, R, ctrl.getJobs);
opsRouter.get('/job-executions', authenticate, R, ctrl.getJobExecutions);
opsRouter.post('/health-check', authenticate, F, S, ctrl.postHealthCheck);
opsRouter.get('/health-checks', authenticate, R, ctrl.getHealthChecks);
opsRouter.get('/rate-limits', authenticate, R, ctrl.getRateLimits);
opsRouter.post('/rate-limits', authenticate, F, S, ctrl.postRateLimit);
opsRouter.get('/retention', authenticate, R, ctrl.getRetention);
opsRouter.post('/retention', authenticate, F, S, ctrl.postRetention);
opsRouter.get('/errors', authenticate, R, ctrl.getErrors);
opsRouter.get('/services', authenticate, R, ctrl.getServices);
opsRouter.get('/service-statuses', authenticate, R, ctrl.getServiceStatuses);
